# Create a logistic regression to predict absenteeism

## Import libraries

In [1]:
import pandas as pd
import numpy as np

## Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day_of_the_week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   
5         0         0         0         1            7                4   
6         0         0         0         1            7                4   
7         0         0         0         1            7                4   
8         0         0         1         0            7                0   
9         0         0         0         1            7                0   

         Date  Transportation Expense  Distance to Work  \
0  2015-07-07                     289                36   
1  2015-07-14                     118                13   
2  2015-07-15                     179                51   
3  2015-07-16                     279                 5   
4  2015-07-23                     289                36   
5  2015-07-10                     179                51   
6  2015-07-17                     361                52   
7  2015-07-24                     260                50   
8  2015-07-06                     155                12   
9  2015-07-13                     235                11   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   
5                  239.554               31          0         0     0   
6                  239.554               27          0         1     4   
7                  239.554               23          0         4     0   
8                  239.554               25          0         2     0   
9                  239.554               29          1         1     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  
5                          2  
6                          8  
7                          4  
8                         40  
9                          8

## Create the targets

In [4]:
# Taking the median values of time of absenteeism as a cutoff
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
# Less than 3 hours of absence is zero, otherwise it is a one. These are the targets
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day_of_the_week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   
5         0         0         0         1            7                4   
6         0         0         0         1            7                4   
7         0         0         0         1            7                4   
8         0         0         1         0            7                0   
9         0         0         0         1            7                0   

         Date  Transportation Expense  Distance to Work  \
0  2015-07-07                     289                36   
1  2015-07-14                     118                13   
2  2015-07-15                     179                51   
3  2015-07-16                     279                 5   
4  2015-07-23                     289                36   
5  2015-07-10                     179                51   
6  2015-07-17                     361                52   
7  2015-07-24                     260                50   
8  2015-07-06                     155                12   
9  2015-07-13                     235                11   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   
5                  239.554               31          0         0     0   
6                  239.554               27          0         1     4   
7                  239.554               23          0         4     0   
8                  239.554               25          0         2     0   
9                  239.554               29          1         1     1   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0  
5                          2                      0  
6                          8                      1  
7                          4                      1  
8                         40                      1  
9                          8                      1

## Comments

In [8]:
# Use of median makes data unbiased
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1) # Checkpoint creation
data_with_targets = data_preprocessed.drop(['Date'], axis = 1)

In [10]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day_of_the_week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Daily Work Load Average  \
0                     289                36                  239.554   
1                     118                13                  239.554   
2                     179                51                  239.554   
3                     279                 5                  239.554   
4                     289                36                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs for regression

In [11]:
data_with_targets.shape

(700, 15)

In [12]:
type(data_with_targets)

pandas.core.frame.DataFrame

In [13]:
data_with_targets.iloc[:,:13] # or data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month_Value  Day_of_the_week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Daily Work Load Average  \
0                       289                36                  239.554   
1                       118                13                  239.554   
2                       179                51                  239.554   
3                       279                 5                  239.554   
4                       289                36                  239.554   
..                      ...               ...                      ...   
695                     179                22                  237.656   
696                     225                26                  237.656   
697                     330                16                  237.656   
698                     235                16                  237.656   
699                     291                31                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 13 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:13]
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_Value',
       'Day_of_the_week', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

## Standardization of inputs

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() # Empty StandardScaler object

# Building a custom scaler to only standardize numerical variables and not categorical ones (or dummies)

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns): #columns decides which variables you choose to standardize.
        self.scaler.fit = StandardScaler()
        self.columns = self
        self.mean = None
        self.var_ = None
        
    def fit(self, X, y=None, copy=None):
        self.scaler.fit(X[self.columns], y)
        self.mean = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled],axis=1)[init_col_order]

In [16]:
dummies = unscaled_inputs[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']]
to_scale = unscaled_inputs[['Month_Value',
       'Day_of_the_week', 'Transportation Expense', 'Distance to Work', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets']]
 
scaler.fit(to_scale)
 
scaled_inputs_no_dummies = scaler.transform(to_scale)
 
dummies = dummies.to_numpy()
 
scaled_inputs_alt = []
for i in range(dummies.shape[0]):
    scaled_inputs_alt.append(np.concatenate((scaled_inputs_no_dummies[i], dummies[i])))
    
scaled_inputs_alt = np.array(scaled_inputs_alt)


In [17]:
scaled_inputs_alt.shape

(700, 13)

columns_to_scale = ['Month_Value',
       'Day_of_the_week', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']

## Train-Test Split and Shuffle

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
train_test_split(scaled_inputs_alt, targets)

[array([[ 1.32476605, -1.35968157,  0.38712192, ...,  0.        ,
          1.        ,  0.        ],
        [ 0.18272635,  0.66825259, -0.6541427 , ...,  0.        ,
          1.        ,  1.        ],
        [ 1.03925612, -0.68370352, -1.57468098, ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [-1.24482327,  1.34423065, -0.6541427 , ...,  0.        ,
          1.        ,  0.        ],
        [ 0.46823627, -0.00772546,  0.68893775, ...,  0.        ,
          0.        ,  1.        ],
        [-0.67380342, -0.00772546, -0.6541427 , ...,  0.        ,
          0.        ,  0.        ]]),
 array([[ 0.46823627, -1.35968157,  0.56821142, ...,  0.        ,
          1.        ,  0.        ],
        [ 1.61027597,  0.66825259,  0.04003371, ...,  0.        ,
          1.        ,  0.        ],
        [-1.53033319, -0.68370352, -1.57468098, ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [ 1.61027597, -1.35968157, -0.98614011, ...,  

In [20]:
x_train, x_test, y_train, y_test  = train_test_split(scaled_inputs_alt, targets, train_size = 0.8, random_state = 20)

In [21]:
print(x_train.shape, y_train.shape)

(560, 13) (560,)


In [22]:
print(x_test.shape, y_test.shape)

(140, 13) (140,)


## Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training

In [24]:
reg = LogisticRegression()

In [25]:
reg.fit(x_train, y_train)

LogisticRegression()

In [26]:
reg.score(x_train, y_train)

0.7732142857142857

### Manual accuracy check

In [27]:
model_outputs = reg.predict(x_train)

In [28]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [29]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [30]:
np.sum((model_outputs == y_train))

433

In [31]:
model_outputs.shape[0]

560

In [32]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7732142857142857

### Finding the intercepts (biases) and coefficients (weights)

In [33]:
reg.intercept_

array([-1.6758377])

In [34]:
reg.coef_

array([[ 1.71463499e-01, -9.43188709e-02,  6.32445487e-01,
         1.65311425e-02, -4.53324018e-04,  1.88234788e-01,
         3.31570984e-01, -2.63214658e-01,  2.79711764e+00,
         8.90732717e-01,  3.08739659e+00,  8.79694173e-01,
        -1.76916286e-01]])

In [35]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_Value',
       'Day_of_the_week', 'Transportation Expense', 'Distance to Work',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [36]:
feature_name = unscaled_inputs.columns.values

In [37]:
summary_table = pd.DataFrame(columns=['Feature Name'], data = feature_name) 

In [38]:
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature Name  Coefficient
0                  Reason_1     0.171463
1                  Reason_2    -0.094319
2                  Reason_3     0.632445
3                  Reason_4     0.016531
4               Month_Value    -0.000453
5           Day_of_the_week     0.188235
6    Transportation Expense     0.331571
7          Distance to Work    -0.263215
8   Daily Work Load Average     2.797118
9           Body Mass Index     0.890733
10                Education     3.087397
11                 Children     0.879694
12                     Pets    -0.176916

In [39]:
summary_table.index = summary_table.index + 1

In [40]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [41]:
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                 Intercept    -1.675838
1                  Reason_1     0.171463
2                  Reason_2    -0.094319
3                  Reason_3     0.632445
4                  Reason_4     0.016531
5               Month_Value    -0.000453
6           Day_of_the_week     0.188235
7    Transportation Expense     0.331571
8          Distance to Work    -0.263215
9   Daily Work Load Average     2.797118
10          Body Mass Index     0.890733
11                Education     3.087397
12                 Children     0.879694
13                     Pets    -0.176916

## Interpreting the coefficients

In [42]:
summary_table['Coefficient'] = summary_table['Coefficient'].astype(float)
summary_table['Odds_ratio'] = np.exp(summary_table['Coefficient'])
summary_table

Feature Name  Coefficient  Odds_ratio
0                 Intercept    -1.675838    0.187151
1                  Reason_1     0.171463    1.187041
2                  Reason_2    -0.094319    0.909993
3                  Reason_3     0.632445    1.882208
4                  Reason_4     0.016531    1.016669
5               Month_Value    -0.000453    0.999547
6           Day_of_the_week     0.188235    1.207117
7    Transportation Expense     0.331571    1.393155
8          Distance to Work    -0.263215    0.768577
9   Daily Work Load Average     2.797118   16.397316
10          Body Mass Index     0.890733    2.436915
11                Education     3.087397   21.919937
12                 Children     0.879694    2.410163
13                     Pets    -0.176916    0.837850

In [43]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature Name  Coefficient  Odds_ratio
11                Education     3.087397   21.919937
9   Daily Work Load Average     2.797118   16.397316
10          Body Mass Index     0.890733    2.436915
12                 Children     0.879694    2.410163
3                  Reason_3     0.632445    1.882208
7    Transportation Expense     0.331571    1.393155
6           Day_of_the_week     0.188235    1.207117
1                  Reason_1     0.171463    1.187041
4                  Reason_4     0.016531    1.016669
5               Month_Value    -0.000453    0.999547
2                  Reason_2    -0.094319    0.909993
13                     Pets    -0.176916    0.837850
8          Distance to Work    -0.263215    0.768577
0                 Intercept    -1.675838    0.187151